In [1]:
# Required imports
import pandas as pd
import altair as alt
import statistics as stats

In [2]:
# Reading .csv file with data
df = pd.read_csv('GLB.Ts_dSST.csv', skiprows=1)
df['year'] = pd.to_datetime(df['Year'], format='%Y')
df

,Year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,J-D,D-N,DJF,MAM,JJA,SON,year
0,1880,-0.29,-0.18,-0.11,-0.19,-0.11,-0.23,-0.21,-0.09,-0.16,-0.23,-0.20,-0.23,-0.19,***,***,-0.14,-0.18,-0.20,1880-01-01
1,1881,-0.15,-0.17,0.04,0.04,0.02,-0.20,-0.06,-0.02,-0.13,-0.20,-0.21,-0.10,-0.10,-.11,-.18,0.03,-0.09,-0.18,1881-01-01
2,1882,0.15,0.15,0.04,-0.18,-0.16,-0.26,-0.20,-0.05,-0.10,-0.24,-0.16,-0.24,-0.10,-.09,.06,-0.10,-0.17,-0.17,1882-01-01
3,1883,-0.31,-0.39,-0.13,-0.17,-0.20,-0.12,-0.08,-0.15,-0.20,-0.14,-0.22,-0.16,-0.19,-.20,-.31,-0.16,-0.12,-0.19,1883-01-01
4,1884,-0.15,-0.08,-0.37,-0.42,-0.36,-0.40,-0.34,-0.26,-0.27,-0.24,-0.30,-0.28,-0.29,-.28,-.13,-0.39,-0.34,-0.27,1884-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,2013,0.66,0.55,0.66,0.52,0.57,0.65,0.57,0.65,0.76,0.67,0.78,0.65,0.64,.63,.58,0.58,0.63,0.74,2013-01-01
134,2014,0.73,0.52,0.76,0.77,0.85,0.66,0.56,0.80,0.88,0.81,0.66,0.78,0.73,.72,.63,0.79,0.67,0.78,2014-01-01
135,2015,0.81,0.87,0.90,0.74,0.75,0.79,0.71,0.79,0.81,1.07,1.02,1.10,0.86,.84,.82,0.80,0.76,0.97,2015-01-01
136,2016,1.15,1.34,1.30,1.07,0.90,0.78,0.82,0.99,0.87,0.89,0.90,0.82,0.99,1.01,1.19,1.09,0.86,0.88,2016-01-01
137,2017,0.96,1.11,1.13,0.93,0.88,0.70,0.81,0.86,0.74,0.88,0.87,0.89,0.90,.89,.96,0.98,0.79,0.83,2017-01-01

In [3]:
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
# df = df[months]
# df[:1]
stats.mean(df[months].iloc[0])
stats.mean(df[months].iloc[1])

-0.095

In [4]:
# Distinguishing mean value of the 1880 - 1899 period to create the division (HOTTER - COLDER)
MEAN_1880_1899 = round(stats.mean(df[df['Year'].isin([year for year in range(1880, 1900)])]['J-D']), 2)
MEAN_1880_1899

-0.23

In [5]:
# Selecting only the columns we require to create a plot
df = df[['Year', 'year', 'J-D']]
df.dtypes

Year             int64
year    datetime64[ns]
J-D            float64
dtype: object

In [6]:
# Main chart 
chart = alt.Chart(df).mark_point(
                color='#a58e7c',
                fill='#f26c08',
                opacity=1).encode(
                                x=alt.X('year:T', scale=alt.Scale(zero=False),
                                       axis=alt.Axis(labelColor='#b0b0b0',
                                                     title='Year', 
                                                     tickCount=15,
                                                    labelFontSize=13),
                                       timeUnit = 'year'),
                                y=alt.Y('J-D:Q',
                                        axis=alt.Axis(labelColor='#b0b0b0', 
                                                      format='+', 
                                                      title='Average annual temperature (Â°C)', 
                                                      tickCount=10,
                                                     labelFontSize=13)
                                       ))

In [12]:
# A line of average temperature value during the 1880-1899
line = alt.Chart(pd.DataFrame({'y': [MEAN_1880_1899]})).mark_rule(color='#b2b2b2', strokeWidth=1).encode(y='y')

In [13]:
# A main title 
main_title = alt.Chart(pd.DataFrame({'x': [pd.to_datetime(1883, format='%Y')], 'y': [0.85]})).mark_text(
    text=['Annual Global Surface Temperature,', 'Relative to Late 19th Century Average'],
    align='left',
    fontSize=15,
    fontWeight=700).encode(x=alt.X('x:T', scale=alt.Scale(zero=False),
                           axis=alt.Axis(title=''), timeUnit = 'year'), y='y:Q')

In [14]:
# Annotations of years
annotation1 = alt.Chart(df).mark_text(
    align='left',
    baseline='middle',
    fontSize = 12,
    dx = 7
).encode(
    x=alt.X('year:T', scale=alt.Scale(zero=False),
                           axis=alt.Axis(title=''), timeUnit = 'year'),
    y='J-D:Q',
    text='Year').transform_filter(
    alt.FieldOneOfPredicate(field='Year', oneOf=[1944, 2014, 2015, 2017])
)

annotation2 = alt.Chart(df).mark_text(
    align='right',
    baseline='middle',
    fontSize = 12,
    dx = -7
).encode(
    x=alt.X('year:T', scale=alt.Scale(zero=False),
                           axis=alt.Axis(title=''), timeUnit = 'year'),
    y='J-D:Q',
    text='Year').transform_filter(
    alt.FieldOneOfPredicate(field='Year', oneOf=[1904, 1998])
)

annotation3 = alt.Chart(df).mark_text(
    align='left',
    baseline='middle',
    fontSize = 12,
    dx = 7,
    fontStyle='bold'
).encode(
    x=alt.X('year:T', scale=alt.Scale(zero=False),
                           axis=alt.Axis(title=''), timeUnit = 'year'),
    y='J-D:Q',
    text='Year').transform_filter(
    alt.FieldOneOfPredicate(field='Year', oneOf=[2016])
)

In [15]:
# Text on the line
hotter = alt.Chart(pd.DataFrame({'x': [pd.to_datetime(2018, format='%Y')], 'y': [-0.12]})).mark_text(
    text=['HOTTER THAN THE', '1880-1899 AVERAGE'],
    align='right',
    fontSize=11,
    fontWeight=300).encode(x=alt.X('x:T', scale=alt.Scale(zero=False),
                           axis=alt.Axis(title=''), timeUnit = 'year'), y='y:Q')

colder = alt.Chart(pd.DataFrame({'x': [pd.to_datetime(2018, format='%Y')], 'y': [-0.28]})).mark_text(
    text='COLDER',
    align='right',
    fontSize=11,
    fontWeight=300).encode(x=alt.X('x:T', scale=alt.Scale(zero=False),
                           axis=alt.Axis(title=''), timeUnit = 'year'), y='y:Q')

In [17]:
# Combination of all layers
alt.layer(chart, line, main_title, annotation1, annotation2, annotation3, hotter, colder).properties(
                        width=800,
                        height=450
                    ).configure_point(
                    size=50
                ).configure_axis(domain=False)

alt.LayerChart(...)

#### Things to be added:
1. Buttons with the ability of interaction with a plot
2. Celsius symbols on y axis